name: clang-tidy

on:
  push:
    paths-ignore:
      - 'README.md'
  pull_request:
    paths-ignore:
      - 'README.md'

jobs:
  clang-tidy:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4

    - run: sudo apt-get update -yq

    - run: sudo apt-get install -yq clang-tidy

    - run: find include/ src/ -name '*.?pp' | xargs -I '{}' clang-tidy --quiet '{}' -- -Iinclude
